# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md013.md
MD013:
  tables: false

# MD033/no-inline-html : Inline HTML : https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md033.md
MD033: false

# MD041/first-line-heading: First Linea Heading : https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md041.md
MD041: false
